[package]
name = "tansu-proxy"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

# [lints]
# workspace = true

[dependencies]
clap.workspace = true
tansu-kafka-sans-io = { path = "../tansu-kafka-sans-io" }
thiserror.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
